version: "3.3"

services:
  frontend:
    stdin_open: true
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./fe:/app
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8002:3000"
    networks:
      - network_nginx
      - my-network 
   

  nginx:
   container_name: nginx
   image: nginx:latest
   ports:
     - "80:80"
   volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./fe:/frontend
   depends_on:
     web:
      condition: service_started
   networks:
      - network_nginx


networks:
  network_nginx:
  
